Algoritmo "Entrada e Saida de Dados"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/04/2020
Var

   nome: caractere
   nota: inteiro


Inicio

      escreval ("Digite o seu nome: ")
      leia(nome)
      escreval ("Digite a sua idade: ")
      leia (nota)
      
      escreval ("O nome digitado foi ",nome)
      escreval ("A idade digitada foi ",nota)


Fimalgoritmo