Algoritmo "Variaveis"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/04/2020
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereco

          primeiroNome, segundoNome, idade, cidade, endereo: caractere
          idade: inteiro
          
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo